service: github-home
frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: af-south-1
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
  iamRoleStatements:
    ${file(aws-resources/role-statements.yml)}


plugins:
  - serverless-prune-plugin
  - serverless-offline


package:
  exclude:
    - node_modules/**
    - .vscode/**
    - .idea/**
    - .requirements/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - venv/**


custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: read_later
  pythonRequirements:
    noDeploy:
      - botocore==1.17.8
      - boto3==1.14.8
  prune:
    automatic: true
    number: 3


functions:
  feed:
    handler: handler.feed
    events:
      - http:
          path: feed
          method: get

  read_later:
    handler: handler.read_later
    events:
      - http:
          path: feed/later
          method: post


resources:
  - ${file(aws-resources/dynamodb.yml)}
